=head1 NAME

GrowlHelperApp Glue - Control GrowlHelperApp app (com.Growl.GrowlHelperApp)

=head1 SYNOPSIS

    use Mac::Glue;
    my $obj = new Mac::Glue 'GrowlHelperApp';

=head1 DESCRIPTION

See C<Mac::Glue> for complete documentation on base usage and framework.

=head2 Events

=over 4

=item $obj->notify(application_name => TEXT, description => TEXT, title => TEXT, with_name => TEXT, [icon_of_application => TEXT, icon_of_file => insl, image => TIFF, image_from_location => insl, pictimage => PICT, priority => long, sticky => bool])

Post a notification to be displayed via Growl (noti/fygr)

Parameters:

    direct object (----): 
    application_name (appl): name of the application posting the notification.
    description (desc): full text of the notification to display
    title (titl): title of the notification to display
    with_name (name): name of the notification to display
    icon_of_application (iapp): Name of the application whose icon should be used for this notification. For example, 'Mail.app'.
    icon_of_file (ifil): Location of the file whose icon should be used as the image for this notification. Accepts aliases, paths and file:/// URLs. e.g. 'file:///Applications'.
    image (imag): TIFF Image to be used for the notification.
    image_from_location (iurl): Location of the image file to use for this notification. Accepts aliases, paths and file:/// URLs.
    pictimage (pict): PICT Image to be used for the notification.
    priority (prio): The priority of the notification, from -2 (low) to 0 (normal) to 2 (emergency).
    sticky (stck): whether or not the notification displayed should time out. Defaults to 'no'.


=item $obj->register(all_notifications => TEXT, as_application => TEXT, default_notifications => TEXT, [icon_of_application => TEXT])

Register an application with Growl (regi/ster)

Parameters:

    direct object (----): 
    all_notifications (anot): list of all notifications to register.
    as_application (appl): name of the application as which to register.
    default_notifications (dnot): list of default notifications to register.
    icon_of_application (iapp): Name of the application whose icon should be used for this notification. For example, 'Mail.app'.


=back

=head2 Classes

=over 4

=item image (TIFF)

=item images (TIFF)

=item picture (PICT)

=item pictures (PICT)

=back

=head1 AUTHOR

Glue created by pudge
using F<gluemac> by Chris Nandor and the Mac::AETE modules
by David C. Schooley.

Copyright (c) 2005.  All rights reserved.  This program is
free software; you can redistribute it and/or modify it under the terms
of the Artistic License, distributed with Perl.

=head1 SEE ALSO

Mac::AppleEvents, Mac::AppleEvents::Simple, macperlcat, Inside Macintosh: 
Interapplication Communication, Mac::Glue, Mac::AETE.

=cut
