#!/usr/bin/python
"""
A python script that sends notifications to the Growl daemon 
See <http://Growl.info> for more information.

Requires Python 2.3 <http://www.python.org/>.

Copyright 2004 Jeremy Rossi <jeremy@jeremyrossi.com>
Released under the BSD license.

Modified by Kevin Ballard <kevin@sb.org>
Updated for Growl 0.6 by Mark Rowe <bdash@users.sourceforge.net>
"""

import Growl
import getopt, sys, os.path

def usage():
    sys.stdout.write("""%s: 
    -n,--name     Specify the name of them Application that is sending the
                  notification [Default: gNotify]
    -i,--icon     Specify a filetype or extension to be used for the icon
    -I,--iconpath Specify a filepath to be used for the icon
                  This option overrides --icon
    --image       Specify an image file to be used for the icon
                  This option overrides --icon and --iconpath
    -t,--title    Title to be used in each notification [Default: gNotify]
    -m,--message  Text to be send to the daemon.  - is used to for stdin
                  For each line (IE: \\n) a new notifaction is sent
    -s,--sticky   Make this notification sticky
    -p,--priority Set the notifcation priority %s
""" % (sys.argv[0], str(Growl.growlPriority.keys())))

NOTIFICATION_NAME = 'Dynamic Messages'

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:], "n:t:m:i:I:sp:",
									["name=", "title=", "message=","icon=","iconpath=","image=","sticky","priority"])
	except getopt.GetoptError:
		# print help information and exit:
		usage()
		sys.exit(2)
	
	appName = "gNotify"
	nTitle = "gNotify"
	nMsg = ""
	nIconType  = ""
	nIconPath  = ""
	nImagePath = ""
	nSticky = False
	nPriority = "Normal"
	for o, a in opts:
		if o in ("-n", "--name"): appName = a
		elif o in ("-t", "--title"): nTitle = a
		elif o in ("-m", "--message"): nMsg = a
		elif o in ("-i", "--icon"): nIconType = a
		elif o in ("-I", "--iconpath"): nIconPath = a
		elif o in ("--image"): nImagePath = a
		elif o in ("-s", "--sticky"): nSticky = True
		elif o in ("-p", "--priority"): nPriority = a
	
	nIcon = None
	if nImagePath != '':
		nImagePath = os.path.abspath(nImagePath)
		nIcon = Growl.Image.imageFromPath(nImagePath)
		if not nIcon:
			sys.stderr.write("Couldn't load file %s\n" % nImagePath)
	elif nIconPath != '':
		nIconPath = os.path.abspath(nIconPath)
		nIcon = Growl.Image.imageWithIconForFile(nIconPath)
		if not nIcon:
			sys.stderr.write("Couldn't load icon for %s\n" % nIconPath)
	elif nIconType != '':
		nIcon = Growl.Image.imageWithIconForFileType(nIconType)
		if not nIcon:
			sys.stderr.write("Couldn't load type %s\n" % nIconType)
	if nIcon is None:
		nIcon = Growl.Image.imageWithIconForFileType('unknown')
	if nPriority and nPriority in Growl.growlPriority.keys():
		nPriority = Growl.growlPriority[nPriority]
	elif nPriority:
		nPriority = int(nPriority)

	
	# fetch Terminal app icon
	nAppIcon = Growl.Image.imageWithIconForApplication('Terminal')
	
	class TestGrowlNotifier(Growl.GrowlNotifier):
		applicationName = appName
		notifications = [NOTIFICATION_NAME]
	n = TestGrowlNotifier(applicationIcon=nIcon)
	n.register()
	
	if nMsg == "-":
		while 1:
			i = sys.stdin.readline()
			if not i: break
			n.notify(NOTIFICATION_NAME, nTitle, i, appicon=nAppIcon, sticky=nSticky, priority=nPriority)
	else:
		n.notify(NOTIFICATION_NAME, nTitle, nMsg, icon=nIcon, sticky=nSticky, priority=nPriority)

if __name__ == '__main__':
	main()
