#!/usr/bin/python
import time
import datetime
import Growl
import os
import sys

class timeGrowlNotifier(Growl.GrowlNotifier):
    applicationName = 'Growl Time'
    notifications = ['Running Time - No Error','Running Time - Error']

def run(args):
    n = timeGrowlNotifier(applicationIcon=Growl.Image.imageWithIconForApplication('Terminal'))
    n.register()
    start = time.time()
    exit = os.system(" ".join(args))
    end = time.time()
    start = datetime.datetime.fromtimestamp(start)
    end = datetime.datetime.fromtimestamp(end)
    if exit == 0:
        n.notify(n.notifications[0], 
                 " ".join(args),  
                 'Running Time=%s\nexit code=%s'%((end - start),exit)
                 )
    else:
        n.notify(n.notifications[1], 
                 " ".join(args),
                 'Running Time=%s\nexit code=%s'%((end - start),exit),
                 priority=Growl.growlPriority["High"]
                 )
    
    return exit

if __name__ == '__main__':
    sys.exit(run(sys.argv[1:]))
