.Dd 2004-10-29           \" DATE 
.Dt GROWLNOTIFY 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm growlnotify
.Nd send a notification to Growl
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl hsv
.Op Fl i Ar ext
.Op Fl I Ar filepath
.Op Fl -image Ar filepath
.Op Fl a Ar appname
.Op Fl p Ar priority
.Op Fl H Ar host
.Op Fl u
.Op Fl P Ar password
.Op Fl -port Ar port
.Op Fl n Ar name
.Op Fl m Ar message
.Op Fl t
.Op Ar title
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
posts a distributed notification to Growl.
.Pp
The options are as follows:
.Bl -tag -width Fl
.It Fl h , Fl -help
Displays this help and exit.
.It Fl n , Fl -name Ar name
Sets the application name to register the notification under.
By default 'growlnotify' is used.
.It Ar title
The title of the notification.
.It Fl t , -title
Does nothing.
This is included to make the syntax compatible with gnotify, another Growl example written in a different programming language.
.It Fl m , -message Ar message
Uses
.Ar message
instead of stdin as the notification message (also called description).
If
.Ar message
is '-', stdin is still used.
.It Fl a , -appIcon Ar name
Sets the notification's application icon to the icon for the given application name. If you don't specify a notification icon, this will be used instead of it; if you specify both, the application icon may be used as a badge (that is, displayed in a corner of the notification icon, superimposed on top of it), or the display may show both separately.
.Pp
Icons are not supported by all displays, so this may be ignored.
.It Fl i , Fl -icon Ar ext
Sets the notification icon to the default icon for the given extension or HFS-encoded file type. For example,
.Fl i
mp3 and
.Fl i
\'MP3 ' (note the space in the second example) will both use the icon for MP3 files.
.Pp
Icons are not supported by all displays, so this may be ignored.
.It Fl I , -iconpath Ar path
Sets the notification icon to the given file's icon (the icon you would see in the Finder if you were looking at the file).
.Pp
Icons are not supported by all displays, so this may be ignored.
.It Fl -image Ar path
Sets the notification icon to contents of the given image file. As of Mac OS X 10.3, this file must be in PNG, JPEG, TIFF, PICT, PDF, JPEG 2000, Adobe Photoshop, BMP, .ico, or .icns format. If the image data is in a format Growl doesn't recognize, the notification will still go through, and the icon will be ignored.
.Pp
Icons are not supported by all displays, so this may be ignored anyway.
.It Fl p , -priority Ar priority
Sets the priority for the notification to an int or named key (default is 0).
.Pp
Priority is not supported by all displays, so this may be ignored.
.It Fl s , Fl -sticky
Causes the notification to stick around until clicked.
.Pp
Sticky notifications are not supported by all displays, so this may be ignored.
.It Fl d , Fl -identifier
Sets the identifier for the notification. The identifier is used for
coalescing, which means multiple notifications with the same identifer
will use a single bubble, the latest notification taking precedence.
.Pp
Coalescing is not supported by all displays, so this may be ignored.
.It Fl w , Fl -wait
Causes
.Nm
to wait until the notification is dismissed (either by clicking or timing out)
before it returns.
.It Fl H , Fl -host
Sends the notification to a remote host instead of the local computer.
This option requires the remote host being set up to accept remote notifications.
The argument is the host to send the notification to.
.It Fl P , Fl -password
Sets the password to be used for the remote notification.
This is necessary if the remote host requires a password for remote notifications.
.It Fl u , Fl -udp
Sends the remote notification with UDP instead of Distributed Objects.
.It Fl -port
Sets the port number to use for UDP notifications.
.El
.Pp
.Nm
displays a notification using Growl. If
.Fl m
isn't specified or is set to '-', the message is read from stdin.
If you don't redirect stdin (e.g. with the shell's | or < operators),
.Nm
will be reading from the terminal, and you will need to send EOF (normally, ctrl-D) on an empty line to end the message.
.Pp
If
.Fl p
is used then
.Ar priority
can be an int between -2 and 2 or can be a named key in the following list:
Very Low, Moderate, Normal, High, Emergency.
.Pp                      \" Inserts a space
.Sh EXAMPLES
.Dl % growlnotify --help
.Pp
Displays this help file.
.Pp
.Dl % growlnotify --appIcon Xcode Build complete
.Dl growlnotify has finished building
.Dl ^D
.Pp
Displays a notification telling you that
.Nm
has finished building.
.Pp
.Dl growlnotify --appIcon Xcode Build complete -m 'growlnotify has finished building'
.Pp
The same as the previous one but suitable for embedding in a script (such as a Shell Script phase).
.Pp                      \" Inserts a space
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr stdin 4
.Sh HISTORY           \" Document history if command behaves in a unique manner 
First appeared as an example for Growl 0.5.
