#define yy_create_buffer toc_yy_create_buffer
#define yy_delete_buffer toc_yy_delete_buffer
#define yy_scan_buffer toc_yy_scan_buffer
#define yy_scan_string toc_yy_scan_string
#define yy_scan_bytes toc_yy_scan_bytes
#define yy_flex_debug toc_yy_flex_debug
#define yy_init_buffer toc_yy_init_buffer
#define yy_flush_buffer toc_yy_flush_buffer
#define yy_load_buffer_state toc_yy_load_buffer_state
#define yy_switch_to_buffer toc_yy_switch_to_buffer
#define yyin toc_yyin
#define yyleng toc_yyleng
#define yylex toc_yylex
#define yyout toc_yyout
#define yyrestart toc_yyrestart
#define yytext toc_yytext

#line 19 "toc_scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $NetBSD: flex.skl,v 1.20 2004/02/01 21:24:02 christos Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, yy_size_t len ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ))
#ifdef __GNUC__
    __attribute__((__unused__))
#endif
;
static void yy_flex_free YY_PROTO(( void * ));

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
static yyconst short int yy_accept[528] =
    {   0,
        0,    0,    0,    0,   56,   54,   49,   53,   54,   54,
       51,   54,   50,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   49,   52,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,   49,    0,    2,    0,    0,    1,    0,    0,   50,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   19,    0,    0,   17,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   49,   52,
        3,    3,    2,    3,    3,    1,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    2,    1,    0,
       48,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    0,    0,    0,    0,    0,    0,

        0,   20,    0,    0,   28,   26,    0,    0,    0,   46,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        0,    9,    0,    5,    0,    0,    0,    0,    0,    0,
       42,   31,    0,    0,   10,   12,    0,    0,    0,    0,
        0,    0,    0,   29,   35,    0,    8,    0,    0,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    0,    0,
        0,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   30,    0,   18,    0,    0,    0,    0,    0,
        0,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    0,    0,    4,    0,   32,    0,
        0,   41,    0,    0,   40,    0,    0,    0,    0,    0,
       24,    0,    0,    0,    0,   45,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,   39,    0,
       38,   27,    0,   34,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    7,    0,
        0,   11,    0,   16,   36,    0,   47,    0,   43,   44,
        0,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    0,    0,    0,    0,   37,    0,
        3,    3,    3,    3,    3,    3,    0,    0,   13,   14,
        0,    0,    0,    3,    3,    3,    3,    3,    3,    3,
        0,   33,    0,   21,    0,    3,    3,    3,    3,    3,

        0,    0,    0,    3,    3,    3,    0,   15,    0,    3,
        3,    3,    0,    0,    3,    3,    0,    0,    3,    3,
        0,   23,    3,    3,   22,    3,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    6,    1,    1,    7,    8,    9,   10,
        8,    8,    8,    8,    8,    8,    8,   11,    1,    1,
        1,    1,    1,    1,   12,    1,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
        1,   26,   27,   28,   29,    1,   30,   31,   32,   33,
        1,   34,    1,    1,   35,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   36,    1,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[535] =
    {   0,
        0,   36,   39,   75,  616,  617,  613,  617,   75,   76,
      617,  607,   74,   59,   75,   74,   71,  598,   69,  600,
       76,  587,   79,  580,   78,   88,  584,  593,  101,  617,
        0,  113,  117,    0,  600,  115,   72,  114,  115,   89,
      591,  106,  593,  106,  580,  116,  573,  113,  120,  577,
      586,  598,  131,  617,  132,  106,  617,  138,  596,  144,
      572,  583,  568,  560,  123,  566,  566,  139,  563,  568,
      576,  563,  565,  560,  572,  617,  559,  569,  548,  128,
      559,  569,  552,  566,  566,  553,  563,  549,  154,  617,
        0,  160,    0,  165,  168,    0,  172,  156,  170,  548,

      559,  544,  536,  159,  542,  542,  166,  539,  544,  552,
      539,  541,  536,  548,    0,  535,  545,  524,  155,  535,
      545,  528,  542,  542,  529,  539,  525,  179,  180,  547,
      617,  537,  529,  535,  172,  521,  513,  532,  530,  518,
      526,  514,  513,  523,  524,  519,  508,  519,  517,  172,
      506,  516,  515,  512,  502,  506,  491,  512,  489,  488,
      498,  188,  206,  193,  509,  501,  507,  189,  493,  485,
      504,  502,  490,  498,  486,  485,  495,  496,  491,  480,
      491,  489,  184,  478,  488,  487,  484,  474,  478,  463,
      484,  461,  460,  470,  470,  468,  470,  478,  465,  473,

      463,  617,  470,  450,  617,  617,  449,  468,  451,  617,
      452,  468,  195,  455,  466,  462,  464,  452,  439,  443,
      444,  456,  451,  449,  455,  452,  617,  443,  441,  443,
      451,  438,  446,  436,    0,  443,  423,    0,    0,  422,
      441,  424,    0,  425,  441,  211,  428,  439,  435,  437,
      425,  412,  416,  417,  429,  424,  422,  428,  425,    0,
      422,  422,  413,  617,  414,  404,  407,  414,  413,  418,
      617,  617,  418,  412,  393,  392,  400,  400,  402,  393,
      409,  402,  394,  617,  617,  396,  617,  400,  405,  399,
      399,  390,    0,  391,  381,  384,  391,  390,  395,    0,

        0,  395,  389,  370,  369,  377,  377,  379,  370,  386,
      379,  371,    0,    0,  373,    0,  377,  382,  378,  373,
      374,  355,  361,  373,  366,  372,  367,  367,  368,  356,
      200,  359,  617,  355,  617,  364,  355,  358,  360,  363,
      351,  358,  353,  354,  335,  341,  353,  346,  352,  347,
      347,  348,  336,  202,  339,    0,  335,    0,  344,  335,
      338,  340,  343,  331,  327,  331,  617,  320,  617,  324,
      334,  617,  336,  332,  617,  334,  321,  332,  328,  324,
      617,  325,  312,  315,  315,  617,  311,  315,    0,  304,
        0,  308,  318,    0,  320,  316,    0,  318,  305,  316,

      312,  308,    0,  309,  296,  299,  299,    0,  617,  309,
      617,  617,  297,  284,  288,  291,  286,  289,  302,  289,
      297,  214,  288,    0,  298,    0,    0,  286,  273,  277,
      280,  275,  278,  291,  278,  286,  220,  277,  617,  276,
      276,  617,  275,  617,  617,  269,  617,  269,  617,  617,
      279,    0,  270,  270,    0,  269,    0,    0,  263,    0,
      263,    0,    0,  273,  272,  274,  222,  266,  617,  263,
      268,  270,  224,  262,    0,  259,  258,  253,  617,  617,
      255,  249,  240,  253,  248,    0,    0,  250,  231,  221,
      220,  617,  235,  617,  241,  217,    0,  232,    0,  238,

      237,  217,  218,  234,  214,  215,  214,  617,  228,  212,
        0,  225,  224,  218,  222,  216,  208,  201,  193,  186,
      173,  617,  169,    0,  617,    0,  617,  259,  261,   79,
      263,  265,  267,  269
    } ;

static yyconst short int yy_def[535] =
    {   0,
      527,    1,  527,    3,  527,  527,  527,  527,  528,  529,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      530,  531,  532,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  527,  528,  527,  528,  529,  527,  529,  533,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      530,  531,  530,  531,  532,  530,  532,  534,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  528,  529,  533,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  531,  532,  534,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  527,  527,  527,  527,  527,  527,

      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,

      530,  530,  530,  530,  530,  530,  530,  530,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  527,  527,  527,  527,  527,  527,
      530,  530,  530,  530,  530,  530,  527,  527,  527,  527,
      527,  527,  527,  530,  530,  530,  530,  530,  530,  530,
      527,  527,  527,  527,  527,  530,  530,  530,  530,  530,

      527,  527,  527,  530,  530,  530,  527,  527,  527,  530,
      530,  530,  527,  527,  530,  530,  527,  527,  530,  530,
      527,  527,  530,  530,  527,  530,    0,  527,  527,  527,
      527,  527,  527,  527
    } ;

static yyconst short int yy_nxt[655] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       11,   14,   15,   16,    6,   17,   18,    6,   19,    6,
       20,   21,   22,    6,   23,   24,   25,   26,   27,    6,
        6,    6,   28,    6,    6,   11,   11,   29,   30,   31,
        7,    8,   32,   33,   34,   35,   36,   36,   36,   34,
       37,   38,   39,   31,   40,   41,   31,   42,   31,   43,
       44,   45,   31,   46,   47,   48,   49,   50,   31,   31,
       31,   51,   31,   31,   34,   34,   29,   30,   54,   91,
       57,   60,   60,   60,   61,   66,   63,   62,   64,   68,
       74,   71,   67,   77,   69,   72,   80,  100,   65,   75,

      101,   81,   89,   90,   78,   82,   83,  107,   55,   58,
       57,   84,  108,   85,   53,   53,   93,   86,   56,   56,
      113,   96,   99,   99,   99,  102,  105,  103,  110,  114,
      116,  119,  111,  106,   54,  128,  120,  104,  122,   58,
      121,  117,  129,  123,  136,  124,   94,  137,  152,  125,
       97,   60,   60,   60,  140,   89,   90,  130,  131,  141,
      153,   53,   53,   93,   55,   55,   53,   53,  162,   56,
       56,   58,   96,   56,   56,  185,  163,   99,   99,   99,
      169,  173,   54,  170,   57,  198,  174,  186,  215,   53,
       53,   93,  526,   94,  130,  131,  525,  199,   94,  200,

      248,   97,  231,  275,  276,   97,  216,   56,   56,  524,
       96,  523,   55,   58,  232,  377,  233,  399,  249,  304,
      305,   94,  449,  450,  522,  378,  521,  400,  462,  463,
      479,  480,  486,  487,  520,  519,  518,  517,  516,   97,
      515,  514,  513,  512,  511,  510,  509,  508,  507,  506,
      505,  504,  503,  502,  501,  500,  481,  499,  488,   53,
       53,   56,   56,   92,   92,   95,   95,  130,  130,  164,
      164,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  485,  484,  483,  482,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,

      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,
      451,  448,  447,  446,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  174,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  141,  409,  408,  407,  406,  405,  404,  403,  402,
      401,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,

      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,

      253,  252,  251,  250,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  197,  196,  195,  131,
      194,  193,  192,  191,  190,  189,  188,  187,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  172,  171,
      168,  167,  166,  165,  161,  160,  159,  158,  157,  156,
      155,  154,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  139,  138,  135,  134,  133,  132,  131,   52,

      127,  126,  118,  115,  112,  109,   98,   88,   87,   79,
       76,   73,   70,   59,   52,  527,    5,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527
    } ;

static yyconst short int yy_chk[655] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    4,    9,  530,
       10,   13,   13,   13,   14,   16,   15,   14,   15,   17,
       21,   19,   16,   23,   17,   19,   25,   37,   15,   21,

       37,   25,   29,   29,   23,   25,   26,   40,    9,   10,
       56,   26,   40,   26,   32,   32,   32,   26,   33,   33,
       44,   33,   36,   36,   36,   38,   39,   38,   42,   44,
       46,   48,   42,   39,   53,   55,   48,   38,   49,   56,
       48,   46,   58,   49,   65,   49,   32,   65,   80,   49,
       33,   60,   60,   60,   68,   89,   89,   98,   98,   68,
       80,   92,   92,   92,   53,   55,   94,   94,   94,   95,
       95,   58,   95,   97,   97,  119,   97,   99,   99,   99,
      104,  107,  128,  104,  129,  135,  107,  119,  150,  162,
      162,  162,  523,   92,  164,  164,  521,  135,   94,  135,

      183,   95,  168,  213,  213,   97,  150,  163,  163,  520,
      163,  519,  128,  129,  168,  331,  168,  354,  183,  246,
      246,  162,  422,  422,  518,  331,  517,  354,  437,  437,
      467,  467,  473,  473,  516,  515,  514,  513,  512,  163,
      510,  509,  507,  506,  505,  504,  503,  502,  501,  500,
      498,  496,  495,  493,  491,  490,  467,  489,  473,  528,
      528,  529,  529,  531,  531,  532,  532,  533,  533,  534,
      534,  488,  485,  484,  483,  482,  481,  478,  477,  476,
      474,  472,  471,  470,  468,  466,  465,  464,  461,  459,
      456,  454,  453,  451,  448,  446,  443,  441,  440,  438,

      436,  435,  434,  433,  432,  431,  430,  429,  428,  425,
      423,  421,  420,  419,  418,  417,  416,  415,  414,  413,
      410,  407,  406,  405,  404,  402,  401,  400,  399,  398,
      396,  395,  393,  392,  390,  388,  387,  385,  384,  383,
      382,  380,  379,  378,  377,  376,  374,  373,  371,  370,
      368,  366,  365,  364,  363,  362,  361,  360,  359,  357,
      355,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  334,
      332,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  315,  312,  311,  310,  309,

      308,  307,  306,  305,  304,  303,  302,  299,  298,  297,
      296,  295,  294,  292,  291,  290,  289,  288,  286,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      270,  269,  268,  267,  266,  265,  263,  262,  261,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  245,  244,  242,  241,  240,  237,  236,  234,
      233,  232,  231,  230,  229,  228,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  212,
      211,  209,  208,  207,  204,  203,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,

      187,  186,  185,  184,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  167,  166,
      165,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  134,  133,  132,  130,
      127,  126,  125,  124,  123,  122,  121,  120,  118,  117,
      116,  114,  113,  112,  111,  110,  109,  108,  106,  105,
      103,  102,  101,  100,   88,   87,   86,   85,   84,   83,
       82,   81,   79,   78,   77,   75,   74,   73,   72,   71,
       70,   69,   67,   66,   64,   63,   62,   61,   59,   52,

       51,   50,   47,   45,   43,   41,   35,   28,   27,   24,
       22,   20,   18,   12,    7,    5,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527,  527,  527,  527,  527,  527,  527,
      527,  527,  527,  527
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "toc_scan.l"
#define INITIAL 0
#line 2 "toc_scan.l"
/*
 * toc_scan.l -- lexer for toc files
 *
 * Copyright (C) 2004, 2005, 2006 Svend Sorensen
 * For license terms, see the file COPYING in this distribution.
 */

#include <stdlib.h>
#include <string.h>
#include "cd.h"
#include "toc_parse_prefix.h"
#include "toc_parse.h"

int toc_lineno = 1;
#define NAME 1

#line 723 "toc_scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ))
#ifdef __GNUC__
    __attribute__((__unused__))
#endif
;
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, yy_size_t ));
#endif

#ifdef YY_NEED_STRLEN
static yy_size_t yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, (size_t)yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, (size_t)max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "toc_scan.l"


#line 884 "toc_scan.c"

#if defined(YY_USES_REJECT) && (defined(__GNUC__) || defined(lint))
	/* XXX: shut up `unused label' warning with %options yylineno */
	if (/*CONSTCOND*/0 && yy_full_match)
		goto find_rule;
#endif
	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while (/*CONSTCOND*/ 1 )	/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 528 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 617 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 29 "toc_scan.l"
case 2:
YY_RULE_SETUP
#line 29 "toc_scan.l"
{
		yylval.sval = strdup(yytext + 1);
		yylval.sval[strlen(yylval.sval) - 1] = '\0';
		BEGIN(INITIAL);
		return STRING;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "toc_scan.l"
{
		yylval.sval = strdup(yytext);
		BEGIN(INITIAL);
		return STRING;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "toc_scan.l"
{ BEGIN(NAME); return CATALOG; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "toc_scan.l"
{ yylval.ival = MODE_CD_DA; return CD_DA; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "toc_scan.l"
{ yylval.ival = MODE_CD_ROM; return CD_ROM; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "toc_scan.l"
{ yylval.ival = MODE_CD_ROM_XA; return CD_ROM_XA; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "toc_scan.l"
{ return TRACK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "toc_scan.l"
{ yylval.ival = MODE_AUDIO; return AUDIO; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "toc_scan.l"
{ yylval.ival = MODE_MODE1; return MODE1; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "toc_scan.l"
{ yylval.ival = MODE_MODE1_RAW; return MODE1_RAW; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "toc_scan.l"
{ yylval.ival = MODE_MODE2; return MODE2; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "toc_scan.l"
{ yylval.ival = MODE_MODE2_FORM1; return MODE2_FORM1; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "toc_scan.l"
{ yylval.ival = MODE_MODE2_FORM2; return MODE2_FORM2; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "toc_scan.l"
{ yylval.ival = MODE_MODE2_FORM_MIX; return MODE2_FORM_MIX; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "toc_scan.l"
{ yylval.ival = MODE_MODE2_RAW; return MODE2_RAW; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "toc_scan.l"
{ yylval.ival = SUB_MODE_RW; return RW; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "toc_scan.l"
{ yylval.ival = SUB_MODE_RW_RAW; return RW_RAW; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "toc_scan.l"
{ return NO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "toc_scan.l"
{ yylval.ival = FLAG_COPY_PERMITTED; return COPY; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "toc_scan.l"
{ yylval.ival = FLAG_PRE_EMPHASIS; return PRE_EMPHASIS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "toc_scan.l"
{ yylval.ival = FLAG_FOUR_CHANNEL; return FOUR_CHANNEL_AUDIO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "toc_scan.l"
{ yylval.ival = FLAG_FOUR_CHANNEL; return TWO_CHANNEL_AUDIO; }
	YY_BREAK
/* ISRC is with CD-TEXT items */
case 24:
YY_RULE_SETUP
#line 68 "toc_scan.l"
{ return SILENCE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 69 "toc_scan.l"
{ return ZERO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 70 "toc_scan.l"
{ BEGIN(NAME); return AUDIOFILE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "toc_scan.l"
{ BEGIN(NAME); return DATAFILE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "toc_scan.l"
{ BEGIN(NAME); return FIFO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "toc_scan.l"
{ return START; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "toc_scan.l"
{ return PREGAP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 75 "toc_scan.l"
{ return INDEX; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "toc_scan.l"
{ return CD_TEXT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "toc_scan.l"
{ return LANGUAGE_MAP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "toc_scan.l"
{ return LANGUAGE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 81 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_TITLE;  return TITLE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 82 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_PERFORMER;  return PERFORMER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 83 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_SONGWRITER;  return SONGWRITER; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_COMPOSER;  return COMPOSER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 85 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_ARRANGER;  return ARRANGER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_MESSAGE;  return MESSAGE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_DISC_ID;  return DISC_ID; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 88 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_GENRE;  return GENRE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_TOC_INFO1;  return TOC_INFO1; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_TOC_INFO2;  return TOC_INFO2; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_UPC_ISRC;  return UPC_EAN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_UPC_ISRC;  return ISRC; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "toc_scan.l"
{ BEGIN(NAME); yylval.ival = PTI_SIZE_INFO;  return SIZE_INFO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "toc_scan.l"
{ toc_lineno++; /* ignore comments */ }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "toc_scan.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "toc_scan.l"
{ yylval.ival = atoi(yytext); return NUMBER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "toc_scan.l"
{ return yytext[0]; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 101 "toc_scan.l"
{ toc_lineno++; /* blank line */ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "toc_scan.l"
{ toc_lineno++; return '\n'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "toc_scan.l"
{ fprintf(stderr, "bad character '%c'\n", yytext[0]); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "toc_scan.l"
ECHO;
	YY_BREAK
#line 1255 "toc_scan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 528 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 528 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 527);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
#include <unistd.h>
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	yy_size_t len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, yy_size_t len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
yy_size_t len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, yy_size_t n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
yy_size_t n;
#endif
	{
	register yy_size_t i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static yy_size_t yy_flex_strlen( yyconst char *s )
#else
static yy_size_t yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register yy_size_t n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 105 "toc_scan.l"

