.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "NE_GET_STATUS" "3" "23 January 2007" "neon 0.26.3" "neon API reference"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ne_get_status \- retrieve HTTP response status for request
.SH "SYNOPSIS"
.PP
\fB#include <ne_request.h>\fR
.HP 31
\fBconst\ ne_status\ *\fBne_get_status\fR\fR\fB(\fR\fBconst\ ne_request\ *\fR\fB\fIrequest\fR\fR\fB);\fR
.SH "DESCRIPTION"
.PP
The
\fBne_get_status\fR
function returns a pointer to the HTTP status object giving the result of a request. The object returned only becomes valid once the request has been
\fIsuccessfully\fR
dispatched (the return value of
\fBne_request_dispatch\fR
or
\fBne_begin_request\fR
was zero). The object remains valid until the associated request object is destroyed.
.SH "SEE ALSO"
.PP
ne_status,
ne_request_create
.SH "EXAMPLE"
.PP
Display the response status code of applying the
HEAD
method to some resource.
.sp
.nf
ne_request *req = ne_request_create(sess, "HEAD", "/foo/bar");
if (ne_request_dispatch(req))
   /* handle errors... */
else
   printf("Response status code was %d\\n", ne_get_status(req)\->code);
ne_request_destroy(req);
.fi
