/* mpeg4ip_config.h.  Generated by configure.  */
/* mpeg4ip_config.h.in.  Generated from configure.in by autoheader.  */

/* Power PC Architecture */
/* #undef ARCH_PPC 1 */

/* have intel processor */
/* #undef ARCH_X86 */

/* have alsa enabled for mp4live */
/* #undef HAVE_ALSA */

/* Define to 1 if `time_base' is member of `AVCodecContext'. */
/* #undef HAVE_AVCODECCONTEXT_TIME_BASE */

/* Define to 1 if the system has the type `AVRational'. */
/* #undef HAVE_AVRATIONAL */

/* Define to 1 if you have the <byteswap.h> header file. */
/* #undef HAVE_BYTESWAP_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* enable faac for mp4live */
/* #undef HAVE_FAAC */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* enable ffmpeg for mp4live */
/* #undef HAVE_FFMPEG */

/* defined if ffmpeg is installed */
/* #undef HAVE_FFMPEG_INSTALLED */

/* Define to 1 if `__pos' is member of `fpos_t'. */
/* #undef HAVE_FPOS_T___POS */

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the `getopt_long_only' function. */
#define HAVE_GETOPT_LONG_ONLY 1

/* Define to 1 if you have the `getrusage' function. */
#define HAVE_GETRUSAGE 1

/* Define to 1 if you have the <glib.h> header file. */
/* #undef HAVE_GLIB_H */

/* Have GTK on system */
/* #undef HAVE_GTK */

/* Have GTK 2.0 on system */
/* #undef HAVE_GTK_2_0 */

/* have id3/tag.h */
/* #undef HAVE_ID3_TAG_H */

/* IGMPv3 definition */
/* #undef HAVE_IGMP_V3 */

/* Define to 1 if you have the `inet_ntoa' function. */
#define HAVE_INET_NTOA 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if the system has the type `in_port_t'. */
#define HAVE_IN_PORT_T 1

/* enable IPv6 architecture */
/* #undef HAVE_IPv6 */

/* enable lame for mp4live */
/* #undef HAVE_LAME */

/* Define to 1 if you have the `asound' library (-lasound). */
/* #undef HAVE_LIBASOUND */

/* Define to 1 if you have the `gnugetopt' library (-lgnugetopt). */
/* #undef HAVE_LIBGNUGETOPT */

/* have libmpeg2 decoder library */
/* #undef HAVE_LIBMPEG2 */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the <linux/cdrom.h> header file. */
/* #undef HAVE_LINUX_CDROM_H */

/* have mac */
#define HAVE_MACOSX 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* mp4live can be used */
/* #undef HAVE_MP4LIVE */

/* Define to 1 if you have the `poll' function. */
#define HAVE_POLL 1

/* Define to 1 if you have the `snd_pcm_hw_params_set_rate_resample' function.
*/
/* #undef HAVE_SND_PCM_HW_PARAMS_SET_RATE_RESAMPLE */

/* Define to 1 if you have the `socketpair' function. */
#define HAVE_SOCKETPAIR 1

/* Define to 1 if the system has the type `socklen_t'. */
#define HAVE_SOCKLEN_T 1

/* enable use of srtp library */
/* #undef HAVE_SRTP */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasestr' function. */
#define HAVE_STRCASESTR 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strsep' function. */
#define HAVE_STRSEP 1

/* Define to 1 if the system has the type `struct ip_mreq_source'. */
/* #undef HAVE_STRUCT_IP_MREQ_SOURCE */

/* Define to 1 if you have the <sys/dvdio.h> header file. */
/* #undef HAVE_SYS_DVDIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* enable x264 for mp4live */
/* #undef HAVE_X264 */

/* have xvid.h with 1.0 API */
/* #undef HAVE_XVID10 */

/* have xvid.h */
/* #undef HAVE_XVID_H */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "mpeg4ip"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mpeg4ip 1.5.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mpeg4ip"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.5.0.1"

/* The size of a `bool', as computed by sizeof. */
#define SIZEOF_BOOL 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your processor stores words with the most significant byte
first (like Motorola and SPARC, unlike Intel and VAX). */
#if defined(__BIG_ENDIAN__)
#define WORDS_BIGENDIAN 1
#else
#undef WORDS_BIGENDIAN
#endif

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
