\" 
\" Copyright (C) 2005 Andrew Wellington.
\" All rights reserved.
\" 
\" Redistribution and use in source and binary forms, with or without
\" modification, are permitted provided that the following conditions are met:
\" 
\" 1. Redistributions of source code must retain the above copyright notice,
\" this list of conditions and the following disclaimer.
\" 2. Redistributions in binary form must reproduce the above copyright notice,
\" this list of conditions and the following disclaimer in the documentation
\" and/or other materials provided with the distribution.
\" 
\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
\" WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
\" EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
\" OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
\" ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
\" 
.Dd 17/03/05               \" DATE 
.Dt growlpinger 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm growlpinger
.\" Use .Nm macro to designate other names for the documented program.
.Nd check if Growl is running and ready for messages.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl hv
.Op Fl t Ar timeout
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
determines if GrowlHelperApp is running and ready to accept notifications for
display with the Growl system.
.Pp                      \" Inserts a space
The following options are supported:
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It Fl h                 
Displays the built in help information
.It Fl t Ar timeout
Sets the timeout in seconds before
.Nm
gives up searching for Growl. If not set
.Nm
will continue until Growl is found
.It Fl v
Causes
.Nm
to display verbose information about the status of Growl.
.El                      \" Ends the list
.Pp
.Sh RETURN VALUE
Returns
.Li 0
if Growl is running and ready for notifications,
.Li 1
otherwise
.Pp
.Sh AUTHOR
Copyright (C) 2005 Andrew Wellington.
.Pp
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr growlnotify 1 
.\" .Sh BUGS              \" Document known, unremedied bugs 
.Sh HISTORY           \" Document history if command behaves in a unique manner
First appeared in Growl 0.7
